// This file is generated by scripts/generate-factory-set.mjs.
// Add/remove a factory or change its productType declaration, then regenerate.

import { factoryKeySet, factoryProductTypeSet } from './factory'

export const factorySet = Object.freeze({
  aircraft: factoryKeySet('aircraft', ['freight', 'passenger']),
  report: factoryKeySet('report', ['print', 'spreadsheet']),
})

export type FactorySet = typeof factorySet

export const productTypeSet = Object.freeze({
  aircraft: factoryProductTypeSet(['airliner', 'freighter']),
  report: factoryProductTypeSet(['csv', 'pdf']),
})

export type ProductTypeSet = typeof productTypeSet

export const factoryDefinitionSet = Object.freeze({
  aircraft: Object.freeze({
    freight: Object.freeze({
      key: factorySet.aircraft.freight,
      productType: productTypeSet.aircraft.freighter,
    }),
    passenger: Object.freeze({
      key: factorySet.aircraft.passenger,
      productType: productTypeSet.aircraft.airliner,
    }),
  }),
  report: Object.freeze({
    print: Object.freeze({
      key: factorySet.report.print,
      productType: productTypeSet.report.pdf,
    }),
    spreadsheet: Object.freeze({
      key: factorySet.report.spreadsheet,
      productType: productTypeSet.report.csv,
    }),
  }),
})

export type FactoryDefinitionSet = typeof factoryDefinitionSet
